module.exports={
    development:{
        dialect:'postgres',
        host:'localhost',
        port:'5432',
        database:'claudiafestas',
        username:'carlos',
        password:'123456'
    }
}